# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 15:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mng', models.CharField(blank=True, max_length=30)),
                ('mng_level', models.CharField(blank=True, choices=[('FT', '副厅'), ('ZZ', '正处'), ('FZ', '副处'), ('ZZ', '正科'), ('FK', '副科'), ('KY', '科员'), ('BSY', '办事员')], max_length=6)),
                ('mng_deg', models.CharField(blank=True, max_length=2)),
                ('start_time', models.DateField(blank=True)),
                ('end_time', models.DateField(blank=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_type', models.CharField(blank=True, max_length=12)),
                ('pro_level', models.CharField(blank=True, choices=[('H', '正高'), ('PH', '副高'), ('M', '中级'), ('L', '初级'), ('PL', '员级')], max_length=4)),
                ('pro_deg', models.CharField(blank=True, max_length=4)),
                ('pro', models.CharField(blank=True, max_length=12)),
                ('start_time', models.DateField(blank=True)),
                ('end_time', models.DateField(blank=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileBasic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realname', models.CharField(blank=True, max_length=20)),
                ('gender', models.CharField(blank=True, choices=[('M', '男'), ('F', '女')], default='M', max_length=2)),
                ('id_real', models.CharField(blank=True, max_length=18)),
                ('department', models.CharField(blank=True, max_length=30)),
                ('minority', models.CharField(blank=True, max_length=10)),
                ('party', models.CharField(blank=True, max_length=20)),
                ('dob', models.DateField(blank=True)),
                ('firstwt', models.DateField(blank=True)),
                ('phone', models.IntegerField(blank=True)),
                ('email', models.EmailField(max_length=254)),
                ('pwd_que', models.CharField(blank=True, max_length=128)),
                ('pwd_anw', models.CharField(blank=True, max_length=128)),
                ('address', models.CharField(blank=True, max_length=256)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileEdu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(blank=True, max_length=30)),
                ('edu_rec', models.CharField(blank=True, choices=[('H', '高中'), ('C', '大专'), ('U', '本科'), ('G', '研究生')], max_length=6)),
                ('degree', models.CharField(blank=True, choices=[('B', '学士'), ('M', '硕士'), ('D', '博士')], max_length=4)),
                ('special', models.CharField(blank=True, max_length=30)),
                ('start_time', models.DateField(blank=True)),
                ('end_time', models.DateField(blank=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileProTech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro', models.CharField(blank=True, max_length=10)),
                ('pro_name', models.CharField(blank=True, max_length=12)),
                ('pro_level', models.CharField(blank=True, choices=[('H', '正高'), ('PH', '副高'), ('M', '中级'), ('L', '初级'), ('PL', '员级')], max_length=4)),
                ('ori_time', models.DateField(blank=True)),
                ('depart', models.CharField(blank=True, max_length=16)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileSkillTech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skl', models.CharField(blank=True, max_length=16)),
                ('skl_level', models.CharField(blank=True, choices=[('PSW', '高级技师'), ('SW', '技师'), ('HW', '高级工'), ('MW', '中级工'), ('LW', '初级工'), ('W', '普通工')], max_length=8)),
                ('ori_time', models.DateField(blank=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Skilled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skl', models.CharField(blank=True, max_length=12)),
                ('skl_level', models.CharField(blank=True, choices=[('PSW', '高级技师'), ('SW', '技师'), ('HW', '高级工'), ('MW', '中级工'), ('LW', '初级工'), ('W', '普通工')], max_length=12)),
                ('skl_deg', models.CharField(blank=True, max_length=2)),
                ('start_time', models.DateField(blank=True)),
                ('end_time', models.DateField(blank=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
