# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard', '0005_auto_20160513_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilebasic',
            name='dob',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='profilebasic',
            name='firstwt',
            field=models.DateField(auto_now_add=True),
        ),
    ]
