# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 17:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard', '0006_auto_20160513_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilebasic',
            name='dob',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='profilebasic',
            name='firstwt',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
