# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 17:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard', '0007_auto_20160513_1724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='management',
            old_name='username',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='professional',
            old_name='username',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='profilebasic',
            old_name='username',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='profileedu',
            old_name='username',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='profileprotech',
            old_name='username',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='profileskilltech',
            old_name='username',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='skilled',
            old_name='username',
            new_name='user_id',
        ),
    ]
