# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 18:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard', '0008_auto_20160513_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilebasic',
            name='email',
        ),
    ]
